ktor:
    application:
        modules:
            - com.ktor.ApplicationKt.module
    deployment:
        port: 8082
    database:
        driver: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/dbUser"
        user: "root"
        password: "root"